<?xml version="1.0" encoding="utf-8"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
   
    <xacro:include filename="diff_robot.materials.xacro" />
    
    <xacro:property name="base_length" value="0.8" />
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_height" value="0.2" />
    <xacro:property name="base_mass" value="5.0" /> <!--Kg-->
    <xacro:property name="wheel_mass" value="1.0" />
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_length" value="0.05" />

    <!--LINK-->
    <link name="base_footprint" />

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <material name="blue" />
        </visual>
        <xacro:box_collision l="${base_length}" w="${base_width}" h="${base_height}" xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
        <xacro:box_inertia m="${base_mass}" l="${2*base_length}" w="${2*base_width}" h="${2*base_height}" 
                           xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
    </link>

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <material name="grey" />
            </visual>
            <xacro:cylinder_collision r="${wheel_radius}" l="${wheel_length}" xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            <xacro:cylinder_inertia m="${wheel_mass}" r="${2*wheel_radius}" l="${2*wheel_length}"
                                    xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
        </link>
    </xacro:macro>
    
    <xacro:wheel_link prefix="back_r" />
    <xacro:wheel_link prefix="back_l" />
    
    

    <link name="front_caster">
        <visual>
          <geometry>
             <sphere radius="${wheel_radius}"/>
             <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
          </geometry>
          <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="0.1"/>
            </geometry>
        </collision>
        <inertial>
          <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
          <mass value="0.1" />
          <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
        </inertial>
    </link>
    
    

    <!--JOINT-->
    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>
	
    <joint name="caster_joint" type="fixed">
        <parent link="base_link" />
        <child link="front_caster" />
        <origin xyz="${base_length / 3.0} 0 0" rpy="0 0 0"/>
    </joint>
    
   

    <!--BACK WHEEL JOINTS-->
    <joint name="base_back_r_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="back_r_wheel_link" />
        <origin xyz="${-base_length / 4.0} ${-(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_back_l_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="back_l_wheel_link" />
        <origin xyz="${-base_length / 4.0} ${(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

 
    



    <!-- ***camera config*** -->
    <xacro:property name="camera_length" value="0.01" />
    <xacro:property name="camera_width" value="0.1" />
    <xacro:property name="camera_height" value="0.05" />

    <link name="camera_link">
        <visual>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}" /> 
            </geometry>
            <material name="red" />
        </visual>
        <collision>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}" />
            </geometry>
        </collision>
        <xacro:box_inertia m="0.1" l="${camera_length}" w="${camera_width}" h="${camera_height}" xyz="0 0 0" rpy="0 0 0" />
    </link>

    <joint name="base_camera_joint" type="fixed">
        <parent link="base_link" />
        <child link="camera_link" />
        <origin xyz="${(base_length + camera_length) / 2} 0 ${base_height / 2}" rpy="0 0 0" />
    </joint>



    <!-- ***lidar config*** -->
    <xacro:property name="lidar_length" value="0.07" />
    <xacro:property name="lidar_radius" value="0.04" />
 

    <link name="lidar_link">
        <visual>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}" /> 
            </geometry>
            <material name="red" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}" /> 
            </geometry>
        </collision>
        <xacro:cylinder_inertia m="0.4" r="${lidar_radius}" l="${lidar_length}" xyz="0 0 0" rpy="0 0 0" />
    </link>

    <joint name="base_lidar_joint" type="fixed">
        <parent link="base_link" />
        <child link="lidar_link" />
        <origin xyz="${base_length / 2 - lidar_radius} 0 ${base_height + lidar_length / 2}" rpy="0 0 0" />
    </joint>

   
    

    <!-- ***IMU*** -->
    <xacro:property name="imu_length" value="0.05" />
    <xacro:property name="imu_width" value="0.05" />
    <xacro:property name="imu_height" value="0.05" />

    <link name="imu_link">
	<visual>
	     <geometry>
		     <box size="${imu_length} ${imu_width} ${imu_height}" />
    	     </geometry>
	</visual>
	<collision>
	     <geometry>
		     <box size="${imu_length} ${imu_width} ${imu_height}" />
             </geometry>
        </collision>
        <xacro:box_inertia m="0.1" l="${imu_length}" w="${imu_width}" h="${imu_height}" xyz="0 0 0" rpy="0 0 0"/>
     </link>

     <joint name="imu_joint" type="fixed">
        <parent link="base_link"/>
         <child link="imu_link"/>
         <origin xyz="0 0 0.05"/>
      </joint>
    
    
</robot>
