image_width: 384
image_height: 288
camera_name: "camera"
camera_matrix:
  rows: 3
  cols: 3
  data: [1218.5,	0, 	471.7465, 
  	0, 		1033.1, 306.1185, 
  	0, 		0, 	1]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0, 0, 0, 0, 0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1218.5,	0, 	471.7465,	0, 
  	0, 		1033.1, 306.1185, 	0,
  	0, 		0, 	1,		0]
